### ISSUE TITLE
validation_groups can be a closure

### ISSUE THREAD

**Issue by toooni** [Abhoryo/APYJsFormValidationBundle#22] opened 2012-08-31 14:26 UTC
since Symfony 2.1 the validation_groups of the form view can be closures (http://symfony.com/doc/master/book/forms.html#groups-based-on-submitted-data).
It would be nice if the APYJsFormValidationBundle can be used with them too... at the moment there is thrown an error as followed:

An exception has been thrown during the rendering of a template ("Warning: in_array() expects parameter 2 to be array, object given in .../vendor/apy/jsfv-bundle/APY/JsFormValidationBundle/EventListener/ValidationGroupsListener.php line 35") in The Bundle::template.html.twig at line xx.

**Comment by Abhoryo** [comment] 2012-08-31 14:29
Ok.

**Comment by Abhoryo** [comment] 2012-08-31 14:50
For now I don't have access to the form to do this.

**Comment by toooni** [comment] 2012-08-31 14:58
i just looked a bit into it and maybe it isn't possible to realize something like this in a simple way :S

**Comment by Abhoryo** [comment] 2012-08-31 15:27
The closure for the validation_group needs a Form object but we have only the FormView object.

If your code doesn't need this form object in the closure, we can pass a fake Form object.

**Comment by recipe** [comment] 2012-08-31 16:03
The problem is not misrepresented that the form is not available but that closure is called on form post-bind event.
We generate client-side javascript using any available information which can be retrieved before the form is rendered.

**Comment by toooni** [comment] 2012-08-31 16:10
yes.. so there is no simple way.. the "form object" is what is needed inside the closure.. else it doesn't make sense to have one..
the only (very complex) solution is to use ajax calls for this.. client-side validation using closures in validation_groups is impossible..

**Comment by recipe** [comment] 2012-08-31 16:15
First of all we should fix code to avoid error messages. After that, you'll  be able at least use custom js code.

**Comment by recipe** [comment] 2012-08-31 16:19
In this bundle validation_groups is used only for filtering the fields, that should not be checked.

**Comment by Abhoryo** [comment] 2012-09-03 19:36
Are we close this issue ?

**Closed as completed** 2012-09-03 19:39 UTC
